spring:
  application:
    name: firstTgBot
  datasource:
    schema: app
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/telegram_bot}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      format_sql: true
      show_sql: true
      default_schema: app
  liquibase:
    liquibase-schema: app
#    default-schema: app  что тут что выше одинаково
  ai:
    openai:
      api-key: ${OPENROUTER_TOKEN}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: tngtech/deepseek-r1t2-chimera:free # Example model
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    mode: webhook  # <-- тут переключаем режим: polling | webhook

    webhook:
      external-url: ${WEBHOOK_EXTERNAL_URL}  # публичный https (ngrok/домен)
      path: /tg/webhook                      # относительный путь контроллера
      secret-token: ${WEBHOOK_SECRET:dev-secret}
      allowed-updates: message,callback_query,my_chat_member
      webhook-path: /webhook


api:
  weather:
    url: https://api.weatherapi.com/v1/current.json
    q: Minsk
    token: aef8e054767d406aa97175410252008
    lang: ru
